filter:
    excluded_paths: [protected/vendor]
    paths: [protected/*]
tools:
    php_code_sniffer:
        config:
            standard: "PSR1"
    php_pdepend:
        command: pdepend
    php_cs_fixer:
        config: { level: psr1 }
checks:
    php:
        code_rating: true
        duplication: true        